### PR TITLE
Add rottentomatoes

### PR DESCRIPTION
**Pull request by Paddyk45**
I hate tomatoes

Screenshots:
grafik
--
grafik
--
grafik

Feel free to suggest more info things

### CODE REVIEW

**Comment by mat-1** [comment]
out of scope for my branch of metasearch2 (since i want to keep it easy to maintain for myself by only having features i actually use), would be cool if you ran your own instance with added features though :)

**Comment by mat-1** [comment]
actually i decided to change the direction of metasearch2 (shwecky and hober and baxxy are maintainers now) sooooo i'm reopening this :3

**Comment by mat-1** [comment]
closing because old and i'm not really interested in having this in metasearch, sorry

**Comment by Paddyk45** [comment]
meow

**Pull request closed without merging**
