### PR TITLE
Added support for running in a subdirectory

### PR DESCRIPTION
**Pull request by G2-Games**
I assume you probably don't want this contribution with how I've implemented it here, especially the JS hack. I'm making this pull request in case you do anyway for some reason.

### CODE REVIEW

**Comment by mat-1** [comment]
Hmm, I think a simpler solution to this would just be changing every absolute link to be relative.

**Comment by G2-Games** [comment]
Oh does that work? Now I feel stupid

**Comment by G2-Games** [comment]
I can't seem to get relative paths to work for most things, although it's very possible I don't know what I'm doing. In any case I think I've completed what I wanted to accomplish here, it works for my use case.

Instance here: https://g2games.dev/search

**Comment by G2-Games** [comment]
Closing this as I think it would be best to implement it in a more elegant way.

**Pull request closed without merging**
